select id_convenio,
fl_versao,
nr_siafi,
nr_sigcon,
nr_plano_sigcon,
nome,
objetivo,
dt_publicacao,
dt_vigencia_inicial,
dt_vigencia_final,
dt_vigencia_atual,
tp_instrumento,
tp_pessoa_beneficiada,
qt_pessoa_beneficiada,
vr_concede_public,
vr_emen_parl_public,
vr_interv_public,
vr_contra_public,
vr_rendimentos,
vr_total_public
from dm_convenio

