select id_tempo,
id_procedimento,
id_orgao_demanda,
id_orgao_contrato,
id_situacao_proc,
id_situacao_cont,
id_municipio,
id_contratado,
id_tipo_licitacao,
id_grupo_matserv,
id_classe_matserv,
id_material_servico,
id_item_matserv,
id_processo,
id_contrato,
id_unidade_medida,
id_linha_fornec,
id_item,
id_unidade_orc,
ano_particao,
dt_item_homologa,
qt_item_pedido,
vr_un_referencia,
vr_referencia,
vr_un_homologado,
vr_homologado,
vr_atualizado
from ft_compras

