select id_tempo,
id_favorecido,
id_cargo,
id_funcao_scdp,
id_orgao,
id_pais_origem,
id_estado_origem,
id_cidade_origem,
id_pais_destino,
id_estado_destino,
id_cidade_destino,
id_documento_viagem,
id_tipo_viagem,
id_tipo_viajante,
id_meio_transporte,
id_motivo,
ordem_trecho,
ano_particao,
dt_inicio_trecho,
dt_fim_trecho,
qt_diaria,
vr_diaria,
vr_passagem
from ft_diarias_scdp

