select id_tempo,
id_grupo,
id_funcao,
id_modalidade,
id_indicador_acao,
id_procedencia,
id_programa,
id_categ_econ,
id_subfuncao,
id_fonte,
id_acao,
id_unidade_orc,
id_decreto,
id_credito,
dt_documento,
sqa_unidade_exec,
sqa_unidade_orc,
tp_operacao,
tp_documento,
nr_documento_global,
nr_documento,
cd_transacao,
cd_unidade_orc,
ano_particao,
vr_credito_suplem,
vr_credito_extraord,
vr_credito_especial,
vr_anulacao_credito,
vr_credito_inicial,
vr_credito_autorizado
from ft_orcamento_cred_alt

