# This uses a reusable workflow
name: Reusable Workflow to add a project to issues

on:
  issues:
    types: [opened]

jobs:
  do-it:
    uses: gabrielbdornas/reusable-workflows/.github/workflows/add_project_to_issue_reusable.yml@main
    secrets:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        USER: ${{ secrets.USER }}
        TYPE: ${{ secrets.TYPE }}
        PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}

  update-project:
    name: Update field(s) on @work-dta project
    runs-on: ubuntu-latest
    needs: do-it
    steps:
      - name: Update Rotina - Atividade - Meta
        id: update_rotina_atividade_meta
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          organization: ${{ secrets.USER }}
          project_number: ${{ secrets.PROJECT_NUMBER }}
          content_id: ${{ github.event.client_payload.command.resource.id }}
          field: "Rotina - Atividade - Meta"
          value: "Atualização de dados - Criação e/ou atualização de dados - Manter conjuntos Age7 atualizados"      