name: Update status on project board
on:
  issues:
    types: [closed]
jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: Read status
        id: read_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          organization: ${{ secrets.USER }}
          project_number: ${{ secrets.PROJECT_NUMBER }}
          operation: read
          content_id: ${{ github.event.client_payload.command.resource.id }}
      - name: Output status
        run: |
          echo "Current status value: ${{ steps.read_status.outputs.field_read_value }}"
      - name: Update status
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          organization: ${{ secrets.USER }}
          project_number: ${{ secrets.PROJECT_NUMBER }}
          content_id: ${{ github.event.client_payload.command.resource.id }}
          field: "Rotina - Atividade - Meta"
          value: "Atualização de dados - Criação e/ou atualização de dados - Manter conjuntos Age7 atualizados"